# -*- coding: utf-8 -*-
"""lab_2_answers_20221-3-60-033.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z9pP9yC_84VlwZ4XPBh-S9GKtSPd3JJa
"""



"""**Create** a 1D NumPy array of integers from 0 to 9"""

import numpy as np

array = np.arange(10)
print(array)



"""Generate a 4x4 NumPy array filled with random integers between 0 and 100"""

import numpy as np

array = np.random.randint(0, 100, size=(4, 4))
print(array)

"""**Given a NumPy array arr = np.arange(20).reshape(4, 5), extract the subarray containing the elements from the 2nd row and 2nd to 4th columns.**"""

import numpy as np

arr = np.arange(20).reshape(4, 5)
array = arr[1, 1:4]
print(array)

"""**Create a 3x3 identity matrix using NumPy**"""

import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)

"""**Generate a random 2x3 array of floats between 0 and 1.**"""

import numpy as np

random_array = np.random.rand(2, 3)
print(random_array)

"""** Generate a 5x5 NumPy array filled with random floats between 0 and 1.**"""

import numpy as np

random_array = np.random.rand(5, 5)
print(random_array)

"""** Reshape a 1D array of integers from 1 to 12 into a 3x4 matrix.**"""

import numpy as np

array_1d = np.arange(1, 13)
matrix_3x4 = array_1d.reshape(3, 4)
print(matrix_3x4)

"""**Flatten a 2D array of shape (2, 3) into a 1D array.**"""



"""** Reshape a 1D array of 20 elements into a 4x5 matrixt**"""

import numpy as np


array_1d = np.arange(1, 21)


array_2d = array_1d.reshape(4, 5)
print(array_2d)

"""****Create a 2D NumPy array with shape (3, 3) filled with zeros.****"""

import numpy as np

# Create a 3x3 array filled with zeros
array_zeros = np.zeros((3, 3))
print(array_zeros)